### ISSUE TITLE
Please add a License.txt file

### ISSUE THREAD

**Issue by sbaechler** [torchbox/vagrant-django-template#11]
TL;DR: Software is copyrighted by default. It needs an open source license included with the project to be open source.

I would like to use parts of this template in an open source library of mine, so contributors can easily set up their own development environment. 
That library is also my pre-thesis project and the experts might be checking for copyright violations, which this is theoretically.

I assume that since you published this template on Github you are ok with people using it.

**Comment by nealtodd** [comment]
Hi @sbaechler,

We've added our BSD-style licence to the master branch (66f03c1).

There's a note at the top of the licence to highlight that it applies to the vagrant-django-template repository code but not to any project started from it (a project will end up with a copy of the license file as part of the process).

There's an additional step in the setup (892fc41) to delete the licence file in the created project.

Hope that helps. Good luck with your pre-thesis project!
