### ISSUE TITLE
Accessible on the host machine as http://localhost:8111/

### ISSUE THREAD

**Issue by svschannak** [torchbox/vagrant-django-template#15]
Hello,

it says in your README-File, that i can connect from my host system by port 8111, but the vagrant config is set to :8000 and in my environment the client is only accessible via port 8000. Did i understand something wrong or is the README just misleading?

Thank you for your great work!

**Comment by gasman** [comment]
Hi @svschannak - thanks for reporting! I changed the port number in the most recent round of updates a few weeks back (057722f438134890ce55a1001775baa21a0eaa3b) but it looks like I missed updating the readme. Will fix this now...

**Comment by gasman** [comment]
Fixed in 22b0db582cf07447a1e8821706f580059258b30c
