### ISSUE TITLE
ImportError on setup and manage

### ISSUE THREAD

**Issue by cdl** [torchbox/vagrant-django-template#18]
It looks like the setup process is failing for me, as I seem to be getting an ImportError after `vagrant up`, and `./manage.py` doesn't work either. Both seem to fail with the following error.

```
ImportError: No module named '{{ project_name }}'
```

[Here's the output](https://gist.github.com/cdl/24807c23823234251bc9ee6f18031b44) from `vagrant up` (identical output occurs with `./manage.py` within SSH). I'm using Vagrant 1.8.1.

**Comment by gasman** [comment]
Hi @cdl,
There shouldn't be any occurrences of `{{ project_name }}` in the codebase generated by `django-admin.py startproject` - those should get rewritten to the project name you specified. Did you run this line exactly as written (other than changing `myproject` to the name of your project)?

```
django-admin.py startproject --template https://github.com/torchbox/vagrant-django-template/zipball/master --name=Vagrantfile myproject
```

**Comment by cdl** [comment]
@gasman My apologies - looks like I just didn't RTFM 😅. (I just git clone'd, `cd`'d into the repo, and then ran `vagrant up` - rather than running that `django-admin.py` line). Sorry - will go ahead and close this issue.
