### ISSUE TITLE
symlink to site-packages

### ISSUE THREAD

**Issue by balazs-endresz** [torchbox/vagrant-django-template#5]
I'd like to have the site-packages directory (in the vagrant box) be accessible from the project root. This would make it a lot easier to view or debug third party code from the same editor I'm using for the project files. But I'm not quite sure how do this. Also, this should probably be disabled by default, e.g. commented out in install.sh if that's the place where this can be done.

**Comment by AMongeMoreno** [comment]
Hi, did you get any solution to this problem? It would be a really helpful feature
